#
# libs.versions.toml
#
# This source file is part of the FoundationDB open source project
#
# Copyright 2015-2025 Apple Inc. and the FoundationDB project authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[versions]

# Main dependency versions

antlr = "4.13.2"
# AutoService kept on 1.0-rc6 to avoid annotation being retained in CLASS. See: https://github.com/FoundationDB/fdb-record-layer/issues/1281
autoService = "1.0-rc6"
# AutoService for development which enables incremental builds, cannot be enabled for production builds due to downstream dependencies
autoService-development = "1.0.1"
asciitable = "0.3.2"
caffeine = "3.1.8"
commonscli = "1.5.0"
dropwizard = "4.2.28"
fdb = "7.1.26"
geophile = "2.3.0"
generatedAnnotation = "1.3.2"
grpc = "1.64.1"
grpc-commonProtos = "2.37.0"
gson = "2.13.2"
guava = "33.4.8-jre"
h2 = "1.3.148"
icu = "69.1"
lucene = "8.11.1"
opencsv = "4.6"
javaPoet = "1.12.0"
jsr305 = "3.0.2"
jts = "1.16.1"
log4j = "2.25.3"
prometheus = "0.16.0"
prometheus-grpc = "0.6.0"
protobuf = "3.25.8"
sqlline = "1.12.0"
slf4j = "1.7.36"

# Test-only dependency versions

assertj = "3.26.3"
apache-commonsCollections = "4.4"
apache-commonsMath3 = "3.6.1"
apache-httpclient = "5.2.1"
bndtools = "6.3.1"
diffutils = "4.12"
hamcrest = "2.2"
jcommander = "1.81"
jline = "3.30.4"
junit = "5.14.1"
junit-platform = "1.14.1"
mockito = "3.7.7"
snakeyaml = "2.2"

# Static analysis dependency versions

jacoco = "0.8.5"
spotbugs = "4.9.0"

[libraries]

# Main dependencies

antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
autoService = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
autoService-development = { module = "com.google.auto.service:auto-service", version.ref = "autoService-development" }
asciitable = { module = "de.vandermeer:asciitable", version.ref = "asciitable" }
fdbJava = { module = "org.foundationdb:fdb-java", version.ref = "fdb" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine"}
caffeine-guava = { module = "com.github.ben-manes.caffeine:guava", version.ref = "caffeine"}
commonscli = { module = "commons-cli:commons-cli", version.ref = "commonscli" }
dropwizard = { module = "io.dropwizard.metrics:metrics-core", version.ref = "dropwizard" }
geophile = { module = "com.geophile:geophile", version.ref = "geophile" }
generatedAnnotation = { module = "javax.annotation:javax.annotation-api", version.ref = "generatedAnnotation" }
grpc-commonProtos = { module = "com.google.api.grpc:proto-google-common-protos", version.ref = "grpc-commonProtos" }
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc" }
grpc-inprocess = { module = "io.grpc:grpc-inprocess", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-util = { module = "io.grpc:grpc-util", version.ref = "grpc" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
icu = { module = "com.ibm.icu:icu4j", version.ref = "icu" }
javaPoet = { module = "com.squareup:javapoet", version.ref = "javaPoet" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
jts = { module = "org.locationtech.jts.io:jts-io-common", version.ref = "jts" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-julBinding = { module = "org.apache.logging.log4j:log4j-jul", version.ref = "log4j" }
log4j-slf4jBinding = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
lucene-analyzers = { module = "org.apache.lucene:lucene-analyzers-common", version.ref = "lucene" }
lucene-core = { module = "org.apache.lucene:lucene-core", version.ref = "lucene" }
lucene-highlighter = { module = "org.apache.lucene:lucene-highlighter", version.ref = "lucene" }
lucene-queryParser = { module = "org.apache.lucene:lucene-queryparser", version.ref = "lucene" }
lucene-suggest = { module = "org.apache.lucene:lucene-suggest", version.ref = "lucene" }
prometheus-grpc = { module = "me.dinowernli:java-grpc-prometheus", version.ref = "prometheus-grpc" }
promethus-httpserver = { module = "io.prometheus:simpleclient_httpserver", version.ref = "prometheus" }
promethus-simpleclient = { module = "io.prometheus:simpleclient", version.ref = "prometheus" }
protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
sqlline = { module = "sqlline:sqlline", version.ref = "sqlline" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-julBridge = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }

# Test-only dependencies

assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
apache-commonsCollections = { module = "org.apache.commons:commons-collections4", version.ref = "apache-commonsCollections" }
apache-commonsMath3 = { module = "org.apache.commons:commons-math3", version.ref = "apache-commonsMath3" }
apache-httpclient = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "apache-httpclient" }
bndtools = { module = "biz.aQute.bnd:biz.aQute.bnd.annotation", version.ref = "bndtools" } # see: https://bnd.bndtools.org/chapters/120-install.html
diffutils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "diffutils" }
guava-testlib = { module = "com.google.guava:guava-testlib", version.ref = "guava" }
grpc-testing = { module = "io.grpc:grpc-testing", version.ref = "grpc" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
jcommander = { module = "com.beust:jcommander", version.ref = "jcommander" }
jline = { module = "org.jline:jline", version.ref = "jline" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-vintange = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
lucene-testFramework = { module = "org.apache.lucene:lucene-test-framework", version.ref = "lucene" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }

[bundles]

test-impl = [ "assertj", "hamcrest", "junit-api", "junit-params", "log4j-core", "mockito", "bndtools" ]
test-runtime = [ "junit-engine", "junit-platform", "log4j-slf4jBinding"]
test-compileOnly = [ "autoService", "jsr305" ]

[plugins]

download = { id = "de.undercouch.download", version = "5.6.0" }
gitversion = { id = "com.palantir.git-version", version = "3.1.0" }
jmh = { id = "me.champeau.jmh", version = "0.7.2" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
serviceloader = { id = "com.github.harbby.gradle.serviceloader", version = "1.1.8" }
shadow = { id = "com.gradleup.shadow", version = "8.3.5" }
spotbugs = { id = "com.github.spotbugs", version = "6.1.3" }
versions = { id = "com.github.ben-manes.versions", version = "0.52.0" }
